version: "3.8"
services:
    stable-diffusion-ui:
        build: .
        restart: always
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          # device_ids: ["1"] # 3060 ti
                          capabilities: [gpu]
        volumes:
            - ./data:/app/data
            - ./cache:/root/.cache/huggingface/diffusers
        ports:
            - 5000:5000
        environment:
            # agree to stable diffusion license first
            # https://huggingface.co/CompVis/stable-diffusion-v1-4
            # then get a token from here
            # https://huggingface.co/settings/tokens
            - HUGGINGFACE_AUTH_TOKEN=
            # if you want to use float16 to reduce vram, uncomment
            # - USE_FLOAT16=1
