version: "3.8"
services:
    stable-diffusion-ui:
        build: .
        restart: always
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          # count: 1
                          device_ids: ["1"] # 3060 ti
                          capabilities: [gpu]
        volumes:
            - ./data:/app/data
            - ./cache:~/.cache/huggingface/diffusers
        ports:
            - 5001:5000
