version: "3.8"
services:
    stable-diffusion-ui:
        build: .
        restart: always
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          # device_ids: ["1"] # 3060 ti
                          capabilities: [gpu]
        volumes:
            # agree to stable diffusion license and download sd-v1-4-full-ema.ckpt
            # https://huggingface.co/CompVis/stable-diffusion-v1-4-original
            - ./sd-v1-4-full-ema.ckpt:/app/sd-v1-4-full-ema.ckpt
            - ./data:/app/data
            - ./cache/huggingface:/root/.cache/huggingface
        ports:
            - 5000:5000
        # if you want to use float16 to reduce vram, uncomment
        # environment:
        #     - USE_FLOAT16=1
